### ISSUE TITLE
TNS 3.0 support?

### ISSUE THREAD

**Issue by toddanglin** [NathanWalker/nativescript-coachmarks#4]
Hey Nathan-

Do you know if your plugin is working with TNS 3.0 yet? Didn't seem to work in the app I'm upgrading from 2.5 to 3.0, but not sure if it's my app or the plugin. Just checking before I go down the debugging rabbit hole...

**Comment by NathanWalker** [comment]
@toddanglin I need to update this, thanks for pinging, I'll get this done in next couple days.

**Comment by NathanWalker** [comment]
Actually this should work as it doesn't use any custom view components. Do you have a stacktrace that points to issue with this particular plugin?

**Comment by toddanglin** [comment]
I did some more testing, and this is working! But it seems I need to recalculate the coordinates I'm providing to position the highlights/boxes. I can see some of the tips, but they are now located FAR away from there target zone. :) I assume this is related to underlying DIP changes.

Either way, that's on me. Happy to hear (and see) it's good for 3.0. 👍
