### ISSUE TITLE
 error TS2345: Argument of type '{ view: any; caption: string; }' is not assignable to parameter of type 'ITNSCoachMark'.   Object literal may only specify known properties, and 'view' does not exist in type 'ITNSCoachMark'.

### ISSUE THREAD

**Issue by DeepikaKochar** [NathanWalker/nativescript-coachmarks#8]
Hello,
I am unable to integrate this plugin in my Nativescript angular project. Can you share some sample code for accessing this plugin. I tried but keep on getting this error:  
```
error TS2345: Argument of type '{ view: any; caption: string; }' is not assignable to parameter of type 'ITNSCoachMark'.
  Object literal may only specify known properties, and 'view' does not exist in type 'ITNSCoachMark'.
```

**Comment by r0zar** [comment]
I also am seeing this on an angular project.

**Comment by r0zar** [comment]
I found the issue, for a workaround disable your TS typings for now.

**Comment by DeepikaKochar** [comment]
@r0zar  Thanks for the update 👍  it's working for now.

**Comment by r0zar** [comment]
what did you end up doing for a workaround?

**Comment by DeepikaKochar** [comment]
Updated index.d.ts file as you suggested. Added view?: any; in both TNSCoachMark and ITNSCoachMark.
